/*!
 * \brief Definitions for the board hardware.
 * \ingroup board
 *
 * This contains most of the definitions for the board. There are some additional
 * definitions in the display, expio, and curswitch modules.
 *
 * Copyright 2023-25 AESilky
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef SYSTEM_DEFS_H_
#define SYSTEM_DEFS_H_
#ifdef __cplusplus
extern "C" {
#endif

#include "pico.h"
#include "pico/stdlib.h"
#undef putc     // Undefine so the standard macros will not be used
#undef putchar  // Undefine so the standard macros will not be used

#include "hardware/adc.h"
#include "hardware/exception.h"
#include "hardware/gpio.h"
#include "hardware/i2c.h"
#include "hardware/pio.h"
#include "hardware/spi.h"
#include "hardware/uart.h"
#include "pico/multicore.h"

// ///////////////////////////////////////////
// //// COMMON (both BOARD-0 and BOARD-1) ////
// ///////////////////////////////////////////

#define ADC_INPUT_0             0               // ADC-0 on GPIO-26 (used with 'adc_select_input')
#define ADC_INPUT_1             1               // ADC-1 on GPIO-27 (used with 'adc_select_input')
#define ADC_INPUT_2             2               // ADC-2 on GPIO-28 (used with 'adc_select_input')
#define ADC_CHIP_TEMP           3               // Internal temperature sensor  (used with 'adc_select_input')

// SPI
//
// Note: Values (Pins) are the GPIO number, not the physical pins on the device.
//

// SPI 0 is used for the Display. Display SCL-RD 6.6MHz (150ns) and the
// Expansion I/O. Expansion I/O SCL 10.0MHz (100ns).
// 5MHz will be used to be compatible with both and provide margin.
//
#define SPI_EXP_DISP_DEVICE     spi0            // Hardware SPI to use
#define SPI_EXP_DISP_MISO       16              // DP-21
#define SPI_EXP_DISP_MOSI       19              // DP-25
#define SPI_EXP_DISP_SCK        18              // DP-24
#define SPI_EXP_DISP_SPEED      (5500 * 1000)   // 5.5MHz

// Chip selects for the SPI devices are generated by a 2:4 decoder
// The decoder is driven by GPIO-8 for A0 and GPIO-13 for A1
//
#define SPI_ADDR_0               8              // DP-11
#define SPI_ADDR_1              13              // DP-17
#define SPI_ADDR_MASK           0x00002100      // Mask to set both bits at once: 0000 0000 0000 0000 0010 0001 0000 0000
#define SPI_DISP_CS_ADDR         0              // Display CS is Addr-0
#define SPI_TOUCH_CS_ADDR        1              // Touch Panel CS is Addr-1
#define SPI_EXPANSION_CS_ADDR    2              // Expansion IO is Addr-2
#define SPI_NONE_CS_ADDR         3              // Addr to use to select no SPI device

// UART Functions
//
#define HOST_COMM_UART          uart0           // UART-0 is used to communicate with the host
#define HOST_COMM_TX             0              // DP-1
#define HOST_COMM_RX             1              // DP-2

// Multiplexed Sensor - SENSBANK - Functionality
//
// Three GPIO (outputs) enable 1 of 8 devices. The result is read on another GPIO (input).
// For most, the sensor is digital and will be LOW (0) when it is active. However, it
// is possible that the device provides an analog signal. Therefore, the read is on
// GPIO-26, which is ADC-0. To allow PIO control, the select GPIOs and the input GPIO
// are sequential.
//
#define SENSOR_SEL_A0           20              // DP-26
#define SENSOR_SEL_A1           21              // DP-27
#define SENSOR_SEL_A2           22              // DP-29
#define SENSOR_SEL_MASK         0x00700000      // For updating multiple pins at once (0000 0111 0000 0000 0000 0000 0000 )
#define SENSOR_READ             26              // DP-31
#define SENSOR_READ_ADC         adc0            // ADC-0 is used for analog sensors

// PIO Blocks
//
#define PIO_SENSBANK_BLOCK          pio0            // PIO Block 0 is used to select and read the Multiplexed Sensors
#define PIO_SENSBANK_SM              0              // State Machine 0 is used to read the Sensors
#define PIO_SENSBANK_DREQ           DREQ_PIO0_RX0   // Sensbank DMA DREQ trigger from PIO0-SM0 RXFIFO
#define PIO_SENSBANK_IRQ_ERR        PIO0_IRQ_0      // PIO IRQ to use for sensbank serial read error
#define PIO_SENSBANK_IRQ_ERR_IDX     0              // PIO IRQ index for the sensbank serial read error

// I2C is brought out to connectors to allow external devices like Spektrum XBUS, ADC Devices, etc.
#define I2C_EXTERN              i2c1
#define I2C_EXTERN_SDA           6              // DP-9  Serial Data
#define I2C_EXTERN_SCL           7              // DP-10 Serial Clock
#define I2C_EXTERN_CLK_SPEED     (200 * 1000)   // 200kHz (relaxed 'Fast-Mode', FM is 400kHz)

// IRQ Inputs
//
// The IRQ from the Touch Panel and the Expansion I/O, along with the Wakeup signal
// (from the USB-2 RTS) are OR'ed together and detected on GPIO-3 (DP-5)
#define IRQ_WU_TOUCH_EXP         3               // DP-5
#define SYSIRQ_SB_DMA_FROM_PIO   DMA_IRQ_0       // System DMA IRQ-0 raised when DMA finishes pulling PIO data
#define IRQn_SB_DMA_FROM_PIO     0u              // Use DMA IRQ 0 for finished pulling PIO data

// PWM - Used for a recurring interrupt for scheduled messages, sleep, housekeeping
//
#define CMT_PWM_RECINT_SLICE     7              // RP2040 has 8 slices. Use the last one for this.

// Switch Control
//
#define SWITCH_LONGPRESS_MS 800     // 0.8 seconds (800ms) is considered a 'long press'
#define SWITCH_REPEAT_MS 250        // If a switch is long-pressed, repeat it every 1/4 second.

// The EEPROM is an I2C device on the Sensor board (which may or may not be present)
#define EEPROM_ADDR1    0x50
#define EEPROM_ADDR2    0x51

// The Sensor board (which may or may not be present) has an ADC as an I2C device
#define SB_ADC_ADDR1    0x48
#define SB_ADC_ADDR2    0x49


// ///////////////////////////////////////////
// //////////        BOARD 0        //////////
// ///////////////////////////////////////////
#if (BOARD_ADDR == 0)

// UART Functions
//
#define SERVO_CTRL_UART         uart1           // UART-1 is used to control the bus-servos
#define SERVO_CTRL_TX            4              // DP-6
#define SERVO_CTRL_RX            5              // DP-7
#define SERVO_CTRL_IRQ          UART1_IRQ       // UART-1 IRQ for received data
#define SERVO_CTRL_TX_EN_GPIO    2              // DP-4 The Bus Servo uses a single wire. This enables TX
#define SERVO_CTRL_TX_EN         0              // TX enable is active low
#define SERVO_CTRL_TX_DIS        1              // TX disable is active high

// RC Receiver and Telemetry input from FrSKY SBUS or Spektrum SRXL2
// This is serial input that is decoded using a PIO
// See PIO section for PIO defines...
#define RC_RXTEL_GPIO            9              // DP-12
// STOP input switch (Red Button)
#define STOP_INPUT_SW_GPIO      17              // DP-22
#define STOP_INPUT_SW_PRESSED    0              // Input (digital) is low when the switch is pressed
#define STOP_INPUT_SW_RELEASED   1              // Input (digital) is high when the switch is not pressed
// Sensor/Servo Power Control (Board0)
#define AUX_PWR_CTRL            15              // DP-20
#define SENSVO_PWR_OFF           0              // Disable is LOW
#define SENSVO_PWR_ON            1              // Enable is HIGH

// PIO Blocks
//
#define PIO_RC_BLOCK                pio2            // Radio Control receive uses PIO Block 2 (available on RP2350)
#define PIO_RC_SM_RX                 0              // Radio Control Data-In uses State Machine 0
#define PIO_RC_SM_SRXL2_SI           1              // Radio Control SRXL2 Serial-In uses State Machine 1
#define PIO_RCRX_DREQ               DREQ_PIO2_RX0   // Radio Control DMA DREQ trigger from PIO2-SM0 RXFIFO
#define PIO_RC_SRXL2_SI_DREQ        DREQ_PIO2_RX1   // Radio Control DMA DREQ trigger from PIO2-SM1 RXFIFO (SRXL2)
#define PIO_RCRX_SYSIRQ_ERR         PIO2_IRQ_0      // PIO IRQ-0 raised on receive data error (framing or parity)
#define PIO_RCRX_SYSIRQ_MSG         PIO2_IRQ_1      // PIO IRQ-1 raised on completed SRXL2 message
#define PIO_RCRX_IRQ_ERR_IDX         0              // PIO IRQ index (0/1) for the RC-RX Error
#define PIO_RCRX_IRQ_MSG_IDX         1              // PIO IRQ index (0/1) for the RC-RX Message detector

// IRQ Inputs
//
// The Radio Control Receiver (RC-RX) use PIO2 and DMA interrupts to process incoming RX messages
#define SYSIRQ_RCRX_DMA_FROM_PIO    DMA_IRQ_1       // System DMA IRQ-1 raised when DMA finishes pulling PIO data
#define IRQn_RCRX_DMA_FROM_PIO      1u              // Use DMA IRQ 1 for finished pulling PIO data
#define IRQ_STOP_SW                 STOP_INPUT_SW_GPIO

#endif

// ///////////////////////////////////////////
// //////////        BOARD 1        //////////
// ///////////////////////////////////////////
#if (BOARD_ADDR == 1)

// SPI 0 is used for the Display. Display SCL-RD 6.6MHz (150ns)
#define SPI_DISP_CD             17              // DP-22
// SPI 1 is used for the Touch Panel. Touch Panel SCL-RD 2.5MHz(400ns)
// 2MHz will be used to provide margin.
//
#define SPI_TOUCH_DEVICE        spi1            // Hardware SPI to use
#define SPI_TOUCH_MISO          12              // DP-16
#define SPI_TOUCH_MOSI          11              // DP-15
#define SPI_TOUCH_SCK           10              // DP-14
#define SPI_TOUCH_SPEED         (2000 * 1000)   // 2MHz

// PIO Blocks
//
#define PIO_ROTARY_BLOCK            pio1            // PIO Block 1 is used to decode the quadrature signal
#define PIO_ROTARY_SM                0              // State Machine 0 is used for the rotary quad decode
#define PIO_ROTARY_IRQ              PIO1_IRQ_0      // PIO IRQ to use for Rotary reading change
#define PIO_ROTARY_IRQ_IDX           0              // PIO IRQ index for the Rotary reading change
#define PIO_NEOPIX_BLOCK            pio1            // PIO Block 1 is used for the Neopixel display
#define PIO_NEOPIX_SM                1              // State Machine 1 is used to drive the Neopixel display
#define PIO_NEOPIX_DREQ             DREQ_PIO1_TX1   // DMA DREQ trigger from PIO1-SM1

// Rotary Encoder Input (Board1)
// This is a A/B quadrature encoder that can be decoded using a PIO (must be sequential)
#define ROTARY_A_GPIO           14              // DP-19
#define ROTARY_B_GPIO           15              // DP-20

// Neopixel Display
// See PIO section for PIO defines...
//
#define NEOPIXEL_DRIVE          27              // Neopixel GPIO Drive Pin

// Switch Bank and/or User Switch
//
#define SW_BANK_GPIO            28              // Switch Matrix Bank
#define SW_BANK_ADC             ADC_INPUT_2     // Switch bank is read using ADC-2
#define SW_MAIN_USER_GPIO       28              // Main User Switch is on GPIO28 (or to GND on the Switch Matrix Bank)
#define SW_MAIN_USER_PRESSED     0              // Input (digital) is low when the main switch is pressed
#define SW_MAIN_USER_RELEASED    1              // Input (digital) is high when the main switch is not pressed

// IRQ Inputs
//
#define IRQ_INPUT_SW            SW_BANK_GPIO        // DP-34
#define IRQ_ROTARY_TURN         14                  // DP-19
#endif

#ifdef __cplusplus
}
#endif
#endif // SYSTEM_DEFS_H_
